Avoid double stub or stub in before(:suite)
* causes this exception (cause not well understood):

  rspec-mocks-2.14.6/lib/rspec/mocks.rb:26:in `proxy_for': undefined method `proxy_for' for nil:NilClass (NoMethodError)
  from /Users/peter_v/.rvm/gems/ruby-2.0.0-p451@dbd/gems/rspec-mocks-2.14.6/lib/rspec/mocks.rb:51:in `allow_message'
  from /Users/peter_v/.rvm/gems/ruby-2.0.0-p451@dbd/gems/rspec-mocks-2.14.6/lib/rspec/mocks/syntax.rb:19:in `stub_object'
  from /Users/peter_v/.rvm/gems/ruby-2.0.0-p451@dbd/gems/rspec-mocks-2.14.6/lib/rspec/mocks/syntax.rb:40:in `stub'
  from /Users/peter_v/Documents/data/github/petervandenabeele/dbd_data_engine/spec/support/stub_real_data_dir.rb:2:in `stub_real_data_dir'
  from /Users/peter_v/Documents/data/github/petervandenabeele/dbd_data_engine/spec/spec_helper.rb:19:in `block (2 levels) in <top (required)>'